// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAJAJh8H9lhmeY0IbSrQsvKoAayqVN3w',
    appId: '1:573808593087:web:750e546f5b122211fb9e0a',
    messagingSenderId: '573808593087',
    projectId: 'shopatoz-a4912',
    authDomain: 'shopatoz-a4912.firebaseapp.com',
    storageBucket: 'shopatoz-a4912.firebasestorage.app',
    measurementId: 'G-ZBYB5K9L61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlRsdfnVFXug3QFdlJoiqW5t5uB30PCnU',
    appId: '1:573808593087:android:d2364bf64d2e327ffb9e0a',
    messagingSenderId: '573808593087',
    projectId: 'shopatoz-a4912',
    storageBucket: 'shopatoz-a4912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZYJ8Ct565lv9MtyU7WMosxxA7JiSMkg',
    appId: '1:573808593087:ios:fd6aba0c16df62b6fb9e0a',
    messagingSenderId: '573808593087',
    projectId: 'shopatoz-a4912',
    storageBucket: 'shopatoz-a4912.firebasestorage.app',
    iosBundleId: 'com.example.shopAz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZYJ8Ct565lv9MtyU7WMosxxA7JiSMkg',
    appId: '1:573808593087:ios:fd6aba0c16df62b6fb9e0a',
    messagingSenderId: '573808593087',
    projectId: 'shopatoz-a4912',
    storageBucket: 'shopatoz-a4912.firebasestorage.app',
    iosBundleId: 'com.example.shopAz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwAJAJh8H9lhmeY0IbSrQsvKoAayqVN3w',
    appId: '1:573808593087:web:b261509a5d5bfb65fb9e0a',
    messagingSenderId: '573808593087',
    projectId: 'shopatoz-a4912',
    authDomain: 'shopatoz-a4912.firebaseapp.com',
    storageBucket: 'shopatoz-a4912.firebasestorage.app',
    measurementId: 'G-YE0JDKN7QT',
  );
}
