// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8R19LdbFa6ZlcM0NTDCTSQ2jd5HOkgj8',
    appId: '1:669485530403:web:3d803bbc90b85067ec6096',
    messagingSenderId: '669485530403',
    projectId: 'mobile-app-softech',
    authDomain: 'mobile-app-softech.firebaseapp.com',
    storageBucket: 'mobile-app-softech.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFZD6ncumVQpefVTPsGnPsBz2XG25WtsU',
    appId: '1:669485530403:android:738e15114ed49775ec6096',
    messagingSenderId: '669485530403',
    projectId: 'mobile-app-softech',
    storageBucket: 'mobile-app-softech.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeXEmxOUG7n6H2jqNUgfql_hrN-dgCL-0',
    appId: '1:669485530403:ios:b10b392f0f0b0b27ec6096',
    messagingSenderId: '669485530403',
    projectId: 'mobile-app-softech',
    storageBucket: 'mobile-app-softech.firebasestorage.app',
    iosBundleId: 'com.example.tmobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeXEmxOUG7n6H2jqNUgfql_hrN-dgCL-0',
    appId: '1:669485530403:ios:b10b392f0f0b0b27ec6096',
    messagingSenderId: '669485530403',
    projectId: 'mobile-app-softech',
    storageBucket: 'mobile-app-softech.firebasestorage.app',
    iosBundleId: 'com.example.tmobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8R19LdbFa6ZlcM0NTDCTSQ2jd5HOkgj8',
    appId: '1:669485530403:web:54af8f8bb67ecbbaec6096',
    messagingSenderId: '669485530403',
    projectId: 'mobile-app-softech',
    authDomain: 'mobile-app-softech.firebaseapp.com',
    storageBucket: 'mobile-app-softech.firebasestorage.app',
  );
}
